jobs:
  deploy-eks:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure kubectl
        uses: aws-actions/eks-kubectl-action@v1
        with:
          cluster-name: ${{ secrets.EKS_CLUSTER_NAME }}
          region: ${{ secrets.AWS_REGION }}

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml  # Aplica o manifesto YAML do Kubernetes

      - name: Update Kubernetes Deployment Image
        run: |
          kubectl set image deployment/restaurante-acme restaurante-acme=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/restaurante-acme:${{ env.IMAGE_TAG }}
          kubectl rollout status deployment/restaurante-acme
