apiVersion: v1
kind: Service
metadata:
  namespace: fiap
  name: mysql-svc
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
