apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    secret.reloader.stakater.com/reload: $APP_NAME
  namespace: rcs
  name: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - name: $APP_NAME
          image: $DOCKER_ECR_REPO_URL/$DOCKER_IMAGE_NAME:$BITBUCKET_COMMIT
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: 4080
             protocol: TCP
          resources:
            requests:
              memory: ${LIMITS_MEMORY}
              cpu: ${LIMITS_CPU}
            limits:
              memory: ${LIMITS_MEMORY}
              cpu: ${LIMITS_CPU}
          envFrom:
          - secretRef:
              name: $APP_NAME
          readinessProbe:
            httpGet:
                path: /v1/api/healthcheck
                port: 4080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 20
          livenessProbe:
            httpGet:
                path: /v1/api/healthcheck
                port: 4080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 20
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: pontaltech-eks-production-fortaleza
---
apiVersion: v1
kind: Service
metadata:
  namespace: rcs
  name: $APP_NAME-svc
spec:
  ports:
    - port: 4080
      targetPort: 4080
      protocol: TCP
  type: ClusterIP
  selector:
    app: $APP_NAME
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: rcs
  name: $APP_NAME-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: $APP_NAME.eks.production.pontaltech.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: $APP_NAME-svc
            port:
              number: 4080
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: $APP_NAME
  namespace: rcs
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  data:
  dataFrom:
  - extract:
      key: rcs/$APP_NAME